---
- name: Configure EC2 with NGINX
  hosts: web
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Start NGINX
      service:
        name: nginx
        state: started
        enabled: true
    - name: Copy static site files to web server
      copy:
        src: site/
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0644'
      become: true
