name: Terraform + Ansible CI/CD

on:
  push:
    branches: [ main ]

jobs:
  provision:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_key_name: ${{ secrets.TF_KEY_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Format Check
        working-directory: terraform
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Generate Ansible Inventory
        run: |
          chmod +x generate_inventory.sh
          sh generate_inventory.sh

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.PEM_PRIVATE_KEY }}" > terraform/key.pem
          chmod 400 terraform/key.pem

      - name: Add EC2 host key to known_hosts
        working-directory: terraform
        run: |
          IP=$(terraform output -raw public_ip)  # Get the IP from the terraform output (assuming terraform outputs 'public_ip')
          echo "Adding $IP to known_hosts"
          ssh-keyscan -H $IP >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i terraform/hosts ansible/setup-nginx.yml --private-key terraform/key.pem -u ubuntu
          
      - name: Clean up SSH Key
        run: rm -f terraform/key.pem
